# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "CheckoutUI"
client_id = "c8932e72f67b1c77dbebbc3aa4bfede7"
application_url = "https://myers-catalogs-constructed-organised.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_delivery_customizations"

[auth]
redirect_urls = [
  "https://myers-catalogs-constructed-organised.trycloudflare.com/auth/callback",
  "https://myers-catalogs-constructed-organised.trycloudflare.com/auth/shopify/callback",
  "https://myers-catalogs-constructed-organised.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sid-checkout-extensions.myshopify.com"
