name = "delivery-customization"
type = "delivery_customization"
api_version = "2023-04"

[build]
command = ""
path = "dist/function.wasm"

[ui.paths]
create = "/app/delivery-customization/:functionId/new"
details = "/app/delivery-customization/:functionId/:id"